"""create discoveries table

Revision ID: 92d2b899be12
Revises:
Create Date: 2026-08-13 18:02:15.350333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d2b899be12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=64), nullable=False),
    sa.Column('pair_address', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discoveries_pair_address'), 'discoveries', ['pair_address'], unique=False)
    op.create_index(op.f('ix_discoveries_token_address'), 'discoveries', ['token_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discoveries_token_address'), table_name='discoveries')
    op.drop_index(op.f('ix_discoveries_pair_address'), table_name='discoveries')
    op.drop_table('discoveries')
    # ### end Alembic commands ###
